### ISSUE TITLE
有关把hugo主题放在github page/docs下的问题

### ISSUE THREAD

**Issue by ironyreunion** [JokerQyou/maupassant-hugo#7]
如果使用的github page不是主仓库，而是/docs folder的话，会出现css地址错误，点击阅读全文也会变成了xxx.github.io/xxxgithub.io/具体文章。

请问是我设置问题还是主题还没有完全完善呢？

**Comment by JokerQyou** [comment]
我从你的仓库中没找到原因。可以麻烦更详细地说明一下吗？

- 构建时的目录结构是什么样的？
- Hugo 的版本？
- 站点配置的内容？（如有敏感内容请在发布前自行抹除）

**Comment by JokerQyou** [comment]
Close due to inactivity.
