### ISSUE TITLE
赞赏功能

### ISSUE THREAD

**Issue by cold-eye** [JokerQyou/maupassant-hugo#8]
请问赞赏功能怎么加进去？基于maupassant主题

**Comment by JokerQyou** [comment]
是指基于二维码的赞赏吗？我自己博客这边加了二维码赞赏功能，有需要的话我今天晚上更新到主题里吧。

**Comment by JokerQyou** [comment]
Closed by c267577241cb9faddeea0438c37ccca2239a2f34. 如果还有任何疑问，请重新打开这个 issue。
